### PR TITLE
Fixing type support C/CPP mix on rmw_fastrtps_dynamic_cpp

### LINKED ISSUE #265: Using different typesupports on same node and topic ends in segfault
## Bug report

**Required Info:**

- Operating System:
  - Ubuntu 18.04
- Installation type:
  - Source
- Version or commit hash:
  - Head
- DDS implementation:
  - Fast RTPS
- Client library (if applicable):
  - N/A

#### Steps to reproduce issue
Create a node that registers to an already registered topic but with a different typesupport. If we assume that the node is using rosout log, and that rosout regsiters a publisher in the /rosout topic with C typesupport. You can subscribe to the /rosout topic with a CPP typesupport.

```
#include <iostream>
#include "rclcpp/rclcpp.hpp"
#include <rcl_interfaces/msg/log.hpp>

class MinimalSubscriber : public rclcpp::Node
{
public:
  MinimalSubscriber()
  : Node("minimal_subscriber")
  {
    subscription_ = this->create_subscription<rcl_interfaces::msg::Log>(
      "rosout",
      [this](rcl_interfaces::msg::Log::UniquePtr msg) {
      RCLCPP_INFO(this->get_logger(), "I heard: '%s'", msg->msg.c_str());
    });
  }

private:
  rclcpp::Subscription<rcl_interfaces::msg::Log>::SharedPtr subscription_;
};

int main(int argc, char * argv[])
{
  rclcpp::init(argc, argv);
  rclcpp::spin(std::make_shared<MinimalSubscriber>());
  rclcpp::shutdown();
  return 0;
}

```

#### Expected behavior
Both registered publisher and subscribers should be able to publish and receive messages for the topic.

#### Actual behavior
The process exits with a segfault when receiving a message on the subscribed topic.

#### Additional information
Two different typesupports cannot be in the same topic at the same time.
This is due to the fact that rmw_fastrtps uses the same name to register both typesupports in the FastRTPS Domain. See [code](https://github.com/ros2/rmw_fastrtps/blob/c9e496560d098b0de2e12aee9af31b1b990156ce/rmw_fastrtps_cpp/src/rmw_subscription.cpp#L108)

Disambiguate with a different name (appending or prepending a string) is not possible because the name of the typesupport is directly related to the name of the topic. See [code](https://github.com/ros2/rmw_fastrtps/blob/c9e496560d098b0de2e12aee9af31b1b990156ce/rmw_fastrtps_cpp/src/rmw_subscription.cpp#L108) and [fastrtps TopicData](https://github.com/eProsima/Fast-RTPS/blob/bfbe04e0974758fab68c377800b5fbf2741949b9/include/fastrtps/TopicDataType.h#L87)

Probably happening in other implementations.

### PR DESCRIPTION
**Pull request by MiguelCompany**
This should fix #265 with `rmw_fastrtps_dynamic_cpp`.

### CODE REVIEW

**Comment by MiguelCompany** [comment]
@dirk-thomas This is ready for review!

**Comment by dirk-thomas** [comment]
Packaging job using this patch as well as ros2/ros1_bridge#233: [Build Status](https://ci.ros2.org/job/ci_packaging_linux/298/)

**Comment by dirk-thomas** [comment]
Non-packaging CI builds:
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/9437/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/5124/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/7717/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/9363/)
* Windows-container [Build Status](http://ci.ros2.org/job/ci_windows-container/209/)

**Comment by MiguelCompany** [comment]
Will address failures today

**Comment by MiguelCompany** [comment]
@dirk-thomas I think I have solved the issue.

I was assuming that the entities were always being destroyed, and had an assertion to check all the objects registered on the type registry were unregistered before destroying the registry itself.

But this is not the case on the failing tests, so I have changed the mechanism on the type registry destructor from an assertion to a cleanup.

**Comment by dirk-thomas** [comment]
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/9457/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/5187/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/7734/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/9386/)
* Windows-container [Build Status](http://ci.ros2.org/job/ci_windows-container/227/)

File: rmw_fastrtps_dynamic_cpp/src/type_support_registry.hpp [hunk 1]
```diff
@@ -0,0 +1,72 @@
...
+
+class TypeSupportRegistry
+{
+private:
+  LockedObject<msg_map_t> message_types_;
+  LockedObject<srv_map_t> request_types_;
+  LockedObject<srv_map_t> response_types_;
+
+public:
+  ~TypeSupportRegistry();
```
Comment (hidmic) [inline rmw_fastrtps_dynamic_cpp/src/type_support_registry.hpp]: @MiguelCompany nit: consider making the (default) constructor private.

File: rmw_fastrtps_dynamic_cpp/src/type_support_registry.cpp [hunk 2]
```diff
@@ -0,0 +1,159 @@
...
+  return_type_support(ros_type_support, request_types_);
+}
+
+void TypeSupportRegistry::return_response_type_support(
+  const rosidl_service_type_support_t * ros_type_support)
+{
+  return_type_support(ros_type_support, response_types_);
+}
+
+static TypeSupportRegistry type_registry_instance;
```
Comment (hidmic) [inline rmw_fastrtps_dynamic_cpp/src/type_support_registry.cpp]: @MiguelCompany consider moving this into the function below to avoid having a non trivially constructed object in global scope.

**Comment by MiguelCompany** [comment]
@hidmic I have just addressed your review comments
