### PR TITLE
Retrieve `HistoryQoS` in discovery when available

### LINKED ISSUE #684: get_publishers_info_by_topic does not return qos depth for publishers with fastDDS
## Bug report

**Required Info:**

- Operating System:
  - Ubuntu 20.04
- Installation type:
  - From source
- Version or commit hash:
  - 5EBF27D810C6AB68EEF7D42937CD421D85E50509AE96883239979A1B3A2F4F82
- DDS implementation:
  - fastDDS
- Client library (if applicable):
  - rclcpp

#### Steps to reproduce issue
Noticed this when using foxglove_bridge. They compute the qos depth to use for a subscriber by summing the qos depths of all publishers on that topic. This is not working with fastDDS as get_publishers_info_by_topic reports a qos depth of 0 for any publisher.

Tracing this through the code, I see the comment here which I think indicates the source of the issue https://github.com/ros2/rmw_fastrtps/blob/901339f274fc07fad757fb32bd16f00815217302/rmw_fastrtps_shared_cpp/include/rmw_fastrtps_shared_cpp/qos.hpp#L129

#### Expected behavior
I would expect get_publishers_info_by_topic to report the actual qos depth of publishers

#### Actual behavior
get_publishers_info_by_topic reports all publishers as having a qos depth of 0

### PR DESCRIPTION
**Pull request by Mario-DL**
## Description

This PR adds the HistoryQoS to the entities discovery callback when available.
Related tests PRs

* https://github.com/ros2/rcl/pull/1242
* https://github.com/ros2/ros2cli/pull/1040

Fixes https://github.com/ros2/rmw_fastrtps/issues/684

### Is this user-facing behavior change?

No

### Did you use Generative AI?

No

### Additional Information

Should be backported only to `Kilted`

### CODE REVIEW

**Review by ahcorde — APPROVED** [review]

**Comment by ahcorde** [comment]
Pulls: ros2/rmw_fastrtps#829, ros2/rcl#1242, ros2/ros2cli#1040
Gist: https://gist.githubusercontent.com/ahcorde/e1d6b10259d33a4a01ea1e33a4dc7da6/raw/ddeaa93863d812677523326fe68db8b191509d9d/ros2.repos
BUILD args:  --packages-above-and-dependencies rcl rmw_fastrtps_shared_cpp ros2cli
TEST args:  --packages-above rcl rmw_fastrtps_shared_cpp ros2cli
ROS Distro: rolling
Job: ci_launcher
ci_launcher ran: https://ci.ros2.org/job/ci_launcher/16136
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/23853/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/17917/)
* Linux-rhel [Build Status](http://ci.ros2.org/job/ci_linux-rhel/3256/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/24511/)

File: rmw_fastrtps_shared_cpp/include/rmw_fastrtps_shared_cpp/qos.hpp [hunk 1]
```diff
@@ -175,6 +175,19 @@ rtps_qos_to_rmw_qos(
...
   qos->liveliness_lease_duration = dds_duration_to_rmw(rtps_qos.liveliness.lease_duration);
+
+  if (rtps_qos.history.has_value()) {
+    if (rtps_qos.history->kind == eprosima::fastdds::dds::KEEP_LAST_HISTORY_QOS) {
+      qos->history = RMW_QOS_POLICY_HISTORY_KEEP_LAST;
+    } else if (rtps_qos.history->kind == eprosima::fastdds::dds::KEEP_ALL_HISTORY_QOS) {
+      qos->history = RMW_QOS_POLICY_HISTORY_KEEP_ALL;
+    } else {
+      qos->history = RMW_QOS_POLICY_HISTORY_UNKNOWN;
+    }
```
Comment (fujitatomoya) [inline rmw_fastrtps_shared_cpp/include/rmw_fastrtps_shared_cpp/qos.hpp]: i would use `switch` instead of `if` statement for 2 reasons. the one is possible performance to use jump table with modern compile, the other is that some compilers can warn us if we miss handling the particular enum values in a `switch`.

**Review by fujitatomoya — COMMENTED** [review]
@Mario-DL are you trying to fix particular issue with this PR?

these are RTPS QoS, so i thought there is no history available via discovery process here. the new Fast-DDS supports this history QoS during this discovery process?

**Comment by Mario-DL** [comment]
> @Mario-DL are you trying to fix particular issue with this PR?
> 
> these are RTPS QoS, so i thought there is no history available via discovery process here. the new Fast-DDS supports this history QoS during this discovery process?

Yes (and commonly accepted across vendors). The standard defines the `PID` for the `HistoryQoS` but it is optional to exchange it during discovery since it does not intervene in the matching. In short, we simply made HistoryQoS available in the Data(r/w).

**Review by fujitatomoya — APPROVED** [review]
lgtm with green CI

**Comment by ahcorde** [comment]
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/23889/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/17936/)
* Linux-rhel [Build Status](http://ci.ros2.org/job/ci_linux-rhel/3287/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/24532/)

**Comment by MiguelCompany** [comment]
Thanks for merging @ahcorde. Would be nice to backport this into kilted

**Comment by ahcorde** [comment]
https://github.com/Mergifyio backport kilted

**Comment by emersonknapp** [comment]
@mergifyio backport jazzy humble

@Mario-DL is it possible to backport this feature to Jazzy/Humble? Or is the version of Fast-DDS in use on those platforms too diverged to backport the new discovery information?
