### PR TITLE
Fix matched event issues

### LINKED ISSUE #681: Receive repeated matched event
## Bug report

Get repeated matched event

**Required Info:**

- Operating System:
  - Ubuntu 22.04
- Installation type:
  -  source code
- Version or commit hash:
  - rolling
- DDS implementation:
  - fastdds (7123d353f4e63)
- Client library (if applicable):
  rclcpp

#### Steps to reproduce issue
```c++
#include <chrono>
#include <string>
#include <vector>

#include "rclcpp/rclcpp.hpp"

#include "std_msgs/msg/string.hpp"

using namespace std::chrono_literals;

class MatchedEventDetectNode : public rclcpp::Node
{
public:
  explicit MatchedEventDetectNode(
    const std::string & pub_topic_name)
  : Node("matched_event_detect_node")
  {
    rclcpp::PublisherOptions pub_options;
    pub_options.event_callbacks.matched_callback =
      [this](rclcpp::MatchedInfo & s) {
        RCLCPP_INFO(
          this->get_logger(),
          "Matched Event: %lu, %lu, %lu, %d", s.total_count, s.total_count_change, s.current_count, s.current_count_change);
      };

    pub_ = create_publisher<std_msgs::msg::String>(
      pub_topic_name, 10, pub_options);
  }

private:
  rclcpp::Publisher<std_msgs::msg::String>::SharedPtr pub_;
  std::shared_ptr<std::promise<bool>> promise_;
};

class MultiSubNode : public rclcpp::Node
{
public:
  explicit MultiSubNode(const std::string & topic_name)
  : Node("multi_sub_node"),
    topic_name_(topic_name)
  {}

  rclcpp::Subscription<std_msgs::msg::String>::WeakPtr create_one_sub(void)
  {
    RCLCPP_INFO(this->get_logger(), "Create a new subscription.");
    auto sub = create_subscription<std_msgs::msg::String>(
      topic_name_,
      10,
      [](std_msgs::msg::String::ConstSharedPtr) {});

    subs_.emplace_back(sub);
    return sub;
  }

private:
  std::string topic_name_;
  std::vector<rclcpp::Subscription<std_msgs::msg::String>::SharedPtr> subs_;
};

int main(int argc, char ** argv)
{
  setvbuf(stdout, NULL, _IONBF, BUFSIZ);
  rclcpp::init(argc, argv);

  std::string topic_name_for_detect_pub_matched_event = "pub_topic_matched_event_detect";

  rclcpp::executors::SingleThreadedExecutor executor;

  auto matched_event_detect_node = std::make_shared<MatchedEventDetectNode>(
    topic_name_for_detect_pub_matched_event);

  auto multi_sub_node = std::make_shared<MultiSubNode>(
    topic_name_for_detect_pub_matched_event);

  auto maximum_wait_time = 10s;

  executor.add_node(matched_event_detect_node);
  executor.add_node(multi_sub_node);

  auto sub1 = multi_sub_node->create_one_sub();
  executor.spin_all(maximum_wait_time);

  rclcpp::shutdown();
  return 0;
}
```

#### Expected behavior
Get one matched 
```bash
[INFO] [1680521185.322512787] [multi_sub_node]: Create a new subscription.
[INFO] [1680521185.323981215] [matched_event_detect_node]: Matched Event: 1, 1, 1, 1
```

#### Actual behavior
Get 2 matched events
```bash
[INFO] [1680521185.322512787] [multi_sub_node]: Create a new subscription.
[INFO] [1680521185.323981215] [matched_event_detect_node]: Matched Event: 1, 1, 1, 1
[INFO] [1680521185.324260832] [matched_event_detect_node]: Matched Event: 1, 0, 1, 0
```
#### Additional information

https://github.com/eProsima/Fast-DDS/issues/3395#issuecomment-1491700658   
Current implementation will get repeated notification.

### PR DESCRIPTION
**Pull request by MiguelCompany**
An alternative for #682 that should fix #681

### CODE REVIEW

File: rmw_fastrtps_shared_cpp/src/custom_publisher_info.cpp [hunk 1]
```diff
@@ -358,14 +360,16 @@ void RMWPublisherEvent::update_matched(
 {
   std::lock_guard<std::mutex> lock(on_new_event_m_);
 
-  matched_status_.total_count = total_count;
-  matched_status_.total_count_change += total_count_change;
-  matched_status_.current_count = current_count;
-  matched_status_.current_count_change += current_count_change;
+  if (on_new_event_cb_[RMW_EVENT_PUBLICATION_MATCHED]) {
```
Comment (fujitatomoya) [inline rmw_fastrtps_shared_cpp/src/custom_publisher_info.cpp:363]: If we set the callback via `set_on_new_qos_event_callback`, the same repeated problem can be observed? since it will eventually calls `trigger_event`?

Comment (MiguelCompany) [reply rmw_fastrtps_shared_cpp/src/custom_publisher_info.cpp:363]: I think this would be the expected behavior. When the user sets a callback (for instance, for the event executor), we should first notify the user callback, and then notify the event on any pending `rmw_wait` call.

One thing to notice, if `rmw_take_event` is called within the execution of the callback, the corresponding guard condition trigger value is changed to false [here](https://github.com/ros2/rmw_fastrtps/blob/5913bd46155fdb1c384896f3aa6823d7d2e44301/rmw_fastrtps_shared_cpp/src/custom_publisher_info.cpp#L197)

File: rmw_fastrtps_shared_cpp/src/custom_publisher_info.cpp [hunk 2]
```diff
@@ -267,7 +267,9 @@ void RMWPublisherEvent::set_on_new_event_callback(
     user_data_[event_type] = nullptr;
     on_new_event_cb_[event_type] = nullptr;
 
-    status_mask &= ~rmw_fastrtps_shared_cpp::internal::rmw_event_to_dds_statusmask(event_type);
+    if (RMW_EVENT_PUBLICATION_MATCHED != event_type) {
+      status_mask &= ~rmw_fastrtps_shared_cpp::internal::rmw_event_to_dds_statusmask(event_type);
+    }
```
[the remark this answers is not in the document]
Comment (MiguelCompany) [reply rmw_fastrtps_shared_cpp/src/custom_publisher_info.cpp]: It does not harm to re-enable it.

I added comments describing why we don't disable the statuses on 5918930fe50e6754ddb97619a55eae1b1eb2af80

File: rmw_fastrtps_shared_cpp/src/custom_publisher_info.cpp (hunk 1 above)
Comment (fujitatomoya) [reply rmw_fastrtps_shared_cpp/src/custom_publisher_info.cpp:364]: @MiguelCompany thanks for the explanation!

**Review by fujitatomoya — APPROVED** [review]

**Comment by Barry-Xu-2018** [comment]
There is a problem on take_event.  
e.g.

https://github.com/eProsima/Fast-DDS/blob/master/src/cpp/fastdds/publisher/DataWriterImpl.cpp#L1190-L1208

In get_publication_matched_status(), current_count_change and total_count_change will be set as 0. 
```c++
eturnCode_t DataWriterImpl::get_publication_matched_status(
        PublicationMatchedStatus& status)
{
    if (writer_ == nullptr)
    {
        return ReturnCode_t::RETCODE_NOT_ENABLED;
    }

    {
        std::unique_lock<RecursiveTimedMutex> lock(writer_->getMutex());

        status = publication_matched_status_;
        publication_matched_status_.current_count_change = 0;
        publication_matched_status_.total_count_change = 0;
    }

    user_datawriter_->get_statuscondition().get_impl()->set_status(StatusMask::publication_matched(), false);
    return ReturnCode_t::RETCODE_OK;
}
```

While calling take_event after matched event happen, it will call get_publication_matched_status() to get status. At this time, current_count_change and total_count_change are already set as 0. 

https://github.com/eProsima/rmw_fastrtps/blob/5918930fe50e6754ddb97619a55eae1b1eb2af80/rmw_fastrtps_shared_cpp/src/custom_publisher_info.cpp#L170-L192

So I think if change may be as below (Only avoid triggering event)
```
    matched_status_.total_count = total_count;
    matched_status_.total_count_change += total_count_change;
    matched_status_.current_count = current_count;
    matched_status_.current_count_change += current_count_change;

    matched_changes_ = true;
  if (on_new_event_cb_[RMW_EVENT_PUBLICATION_MATCHED]) {
    trigger_event(RMW_EVENT_PUBLICATION_MATCHED);
  }
```

**Comment by MiguelCompany** [comment]
@Barry-Xu-2018 I think you are right!

Updated the code in 0c60ec2856ce41a039fafec95319c71e5be4a79a

**Comment by fujitatomoya** [comment]
CI:
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/18445/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/12991/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/19132/)

**Comment by fujitatomoya** [comment]
CC: @iuhilnehc-ynos

**Comment by fujitatomoya** [comment]
@MiguelCompany can you address cpplint?

**Comment by Barry-Xu-2018** [comment]
I tried to run matched demo and find a new problem.  It seems repeated event was received. 
I will investigate it.

```bash
ros2 run demo_nodes_cpp matched_event_detect 
[INFO] [1680752983.277148039] [multi_sub_node]: Create a new subscription.
[INFO] [1680752983.278800649] [matched_event_detect_node]: First subscription is connected.
[INFO] [1680752983.278846840] [multi_sub_node]: Create a new subscription.
[INFO] [1680752983.280026632] [matched_event_detect_node]: The changed number of connected subscription is 1 and current number of connected subscription is 2.
[INFO] [1680752983.280062182] [multi_sub_node]: Destroy a subscription.
[INFO] [1680752983.281545152] [matched_event_detect_node]: The changed number of connected subscription is -1 and current number of connected subscription is 1.
[INFO] [1680752983.281580592] [multi_sub_node]: Destroy a subscription.
[INFO] [1680752983.282452240] [matched_event_detect_node]: Last subscription is disconnected.
[INFO] [1680752983.282486114] [multi_pub_node]: Create a new publisher.
[INFO] [1680752983.283396538] [multi_pub_node]: Create a new publisher.
[INFO] [1680752983.284131755] [matched_event_detect_node]: First publisher is connected.
[INFO] [1680752983.284165433] [multi_pub_node]: Destroy a publisher.
[INFO] [1680752983.285238736] [matched_event_detect_node]: The changed number of connected publisher is -1 and current number of connected publisher is 1.
[INFO] [1680752983.285273466] [multi_pub_node]: Destroy a publisher.
[INFO] [1680752983.286016443] [matched_event_detect_node]: Last publisher is disconnected.
```

**Comment by Barry-Xu-2018** [comment]
You can use this code to reproduce the problem.  
https://github.com/Barry-Xu-2018/bug_reproduce/blob/master/rclcpp_bug/src/rmw_fastrtps_681/rmw_fastrtps_681.cpp

While creating or destroying a subscription, publisher get 2 notification of matched event. 
```
[INFO] [1680787176.004999904] [multi_sub_node]: Create a new subscription.
[INFO] [1680787176.007356863] [matched_event_detect_node]: Matched Event: 1, 1, 1, 1
[INFO] [1680787176.007778429] [matched_event_detect_node]: Matched Event: 1, 0, 1, 0
[INFO] [1680787176.009060380] [multi_sub_node]: Destroy a subscription.
[INFO] [1680787176.010856996] [matched_event_detect_node]: Matched Event: 1, 0, 0, -1
[INFO] [1680787176.011048782] [matched_event_detect_node]: Matched Event: 1, 0, 0, 0
``` 
Repeated notification is from 

https://github.com/eProsima/rmw_fastrtps/blob/0c60ec2856ce41a039fafec95319c71e5be4a79a/rmw_fastrtps_shared_cpp/src/rmw_wait.cpp#L194-L199

And repeated notification isn't from `DataWriterImpl::InnerDataWriterListener::onWriterMatched()`.

**Comment by fujitatomoya** [comment]
@MiguelCompany still it still generates the 2 events, is this expected behavior? or we should add if `*_change` is zero, it should be ignored?

**Comment by MiguelCompany** [comment]
@Barry-Xu-2018 @fujitatomoya I think I finally got it right. Please check on your side.

**Comment by fujitatomoya** [comment]
CI:
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/18464/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/13010/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/19159/)

**Comment by Barry-Xu-2018** [comment]
@MiguelCompany 
After testing, the repeat notification also be found.   

In __rmw_init_event, you change code as the below.
```
  bool is_matched_event =
    (RMW_EVENT_PUBLICATION_MATCHED == event_type) ||
    (RMW_EVENT_SUBSCRIPTION_MATCHED == event_type);
  if (!is_matched_event) {
    eprosima::fastdds::dds::StatusMask status_mask =
      event->get_listener()->get_statuscondition().get_enabled_statuses();
    status_mask |= rmw_fastrtps_shared_cpp::internal::rmw_event_to_dds_statusmask(event_type);
    event->get_listener()->get_statuscondition().set_enabled_statuses(status_mask);
  }
```

You don't want to get status notification for matched event.  
But I found code also can run .

https://github.com/ros2/rmw_fastrtps/blob/master/rmw_fastrtps_shared_cpp/src/rmw_wait.cpp#L191-L199

**Comment by Barry-Xu-2018** [comment]
@MiguelCompany 

Status mask already enable matched.  
e.g.
https://github.com/ros2/rmw_fastrtps/blob/851ced88fe7979af847ac0b231e293f9f23a13ae/rmw_fastrtps_cpp/src/publisher.cpp#L268-L272

Maybe we cannot disable it.  
So maybe we have to add check at __wait_set(). Status check ignore matched event or matched event only depend on trigger value.

https://github.com/ros2/rmw_fastrtps/blob/851ced88fe7979af847ac0b231e293f9f23a13ae/rmw_fastrtps_shared_cpp/src/rmw_wait.cpp#L191-L205

**Comment by Barry-Xu-2018** [comment]
Friendly ping @MiguelCompany

**Comment by Barry-Xu-2018** [comment]
@MiguelCompany 

According to the release schedule of Iron

Mon. April 10, 2023 - Alpha + RMW freeze
Preliminary testing and stabilization of ROS Base [1](https://docs.ros.org/en/rolling/Releases/Release-Iron-Irwini.html#id14) packages, and API and feature freeze for RMW provider packages.

I am not sure whether this problem should be fixed today.  
Maybe we can use this temporary method to resolve it (https://github.com/ros2/rmw_fastrtps/pull/683#issuecomment-1499865369).
If have better way, we can update codes late.

**Comment by MiguelCompany** [comment]
@Barry-Xu-2018 @fujitatomoya One last try before using the workaround in https://github.com/ros2/rmw_fastrtps/pull/683#issuecomment-1499865369.

I rebased and changed the way the information of the event is taken, so the status on the entity is always reset.

**Review by iuhilnehc-ynos — APPROVED** [review]

**Comment by Barry-Xu-2018** [comment]
@MiguelCompany Thank you. Your change fixed it after testing.   
I think you can merge this fix.

**Comment by iuhilnehc-ynos** [comment]
re-run CI based on https://github.com/ros2/rmw_fastrtps/pull/683#issuecomment-1499540362

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/18483/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/13031/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/19203/)

**Comment by iuhilnehc-ynos** [comment]
rerun CI with my [repos](https://gist.githubusercontent.com/iuhilnehc-ynos/a6544c0ac62eba5ef9599facc17dff4b/raw/7987ce16f85e6efb8f6f276ab53b3b11390d5c68/ros2.repos) which use the [latest ros2](https://github.com/ros2/ros2/blob/rolling/ros2.repos) with current PR.

CI:

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/18484/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/13032/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/19204/)
