### PR TITLE
Avoid memory leaks and undefined behavior in rmw_fastrtps_dynamic_cpp typesupport code

### LINKED ISSUE #428: [rmw_fastrtps_dynamic_cpp] Typesupport implementation leaks and it relies in conceptually broken cpp
See discussion in:
- https://github.com/ros2/rmw_cyclonedds/issues/219
- https://github.com/ros2/rmw_cyclonedds/pull/228

#228 can directly be applied here.

### PR DESCRIPTION
**Pull request by MiguelCompany**
This fixes #428 by using a similar approach to ros2/rmw_cyclonedds#228

It also addresses #219

### CODE REVIEW

File: rmw_fastrtps_dynamic_cpp/include/rmw_fastrtps_dynamic_cpp/TypeSupport_impl.hpp [hunk 1]
```diff
@@ -55,58 +58,6 @@ SPECIALIZE_GENERIC_C_SEQUENCE(uint32, uint32_t)
...
-    free(sequence->data);
-    sequence->data = nullptr;
-    sequence->size = 0;
-    sequence->capacity = 0;
-  } else {
-    // ensure that data, size, and capacity values are consistent
-    assert(0 == sequence->size);
-    assert(0 == sequence->capacity);
-  }
-}
```
Comment (ivanpauno) [inline rmw_fastrtps_dynamic_cpp/include/rmw_fastrtps_dynamic_cpp/TypeSupport_impl.hpp:108]: I didn't realize that this could be deleted, good point

File: rmw_fastrtps_dynamic_cpp/include/rmw_fastrtps_dynamic_cpp/TypeSupport_impl.hpp [hunk 2]
```diff
@@ -437,26 +289,31 @@ bool TypeSupport<MembersType>::serializeROSmessage(
...
-              subros_message = field;
               array_size = member->array_size_;
             } else {
-              array_size = get_array_size_and_assign_field(
-                member, field, subros_message, sub_members_size, max_align);
+              if (!member->size_function) {
+                RMW_SET_ERROR_MSG("unexpected error: size function is null");
+                return false;
+              }
+              array_size = member->size_function(field);
```
Comment (ivanpauno) [inline rmw_fastrtps_dynamic_cpp/include/rmw_fastrtps_dynamic_cpp/TypeSupport_impl.hpp:301]: does this work?
I think that the `size_function` is for querying the current size, here you want the desired size.
See https://github.com/ros2/rmw_cyclonedds/blob/91aed377a0a2e39664d0eae401ee49e9c419540a/rmw_cyclonedds_cpp/include/rmw_cyclonedds_cpp/TypeSupport_impl.hpp#L375.

File: rmw_fastrtps_dynamic_cpp/include/rmw_fastrtps_dynamic_cpp/TypeSupport_impl.hpp [hunk 3]
```diff
@@ -693,27 +550,32 @@ size_t TypeSupport<MembersType>::getEstimatedSerializedSize(
...
```
Comment (ivanpauno) [inline rmw_fastrtps_dynamic_cpp/include/rmw_fastrtps_dynamic_cpp/TypeSupport_impl.hpp:562]: Unrelated note: I'm not sure why `getEstimatedSerializedSize` is needed here and not in `rmw_cyclonedds`

File: rmw_fastrtps_dynamic_cpp/include/rmw_fastrtps_dynamic_cpp/TypeSupport_impl.hpp (hunk 2 above)
Comment (ivanpauno) [reply rmw_fastrtps_dynamic_cpp/include/rmw_fastrtps_dynamic_cpp/TypeSupport_impl.hpp:301]: I'm sorry, I'm reading this incorrectly.
This is the serializing function, not the deserializing one.

Out of curiosity, why is this needed here and not in `rmw_cyclonedds`?

**Review by ivanpauno — APPROVED** [review]
LGTM! Thanks for the fix @MiguelCompany !!

I have left a few question, but they aren't quite important.

**Comment by ivanpauno** [comment]
CI:
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/12237/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/7215/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/9957/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/12131/)

**Comment by MiguelCompany** [comment]
@ivanpauno I think builds have failed due to #382

File: rmw_fastrtps_dynamic_cpp/include/rmw_fastrtps_dynamic_cpp/TypeSupport_impl.hpp (hunk 1 above)
Comment (MiguelCompany) [reply rmw_fastrtps_dynamic_cpp/include/rmw_fastrtps_dynamic_cpp/TypeSupport_impl.hpp:108]: 😄

File: rmw_fastrtps_dynamic_cpp/include/rmw_fastrtps_dynamic_cpp/TypeSupport_impl.hpp (hunk 2 above)
Comment (MiguelCompany) [reply rmw_fastrtps_dynamic_cpp/include/rmw_fastrtps_dynamic_cpp/TypeSupport_impl.hpp:301]: `rmw_cyclonedds` does have a custom serializer, but it is on another source file ([this one](https://github.com/ros2/rmw_cyclonedds/blob/91aed377a0a2e39664d0eae401ee49e9c419540a/rmw_cyclonedds_cpp/src/serdata.cpp))

File: rmw_fastrtps_dynamic_cpp/include/rmw_fastrtps_dynamic_cpp/TypeSupport_impl.hpp (hunk 3 above)
Comment (MiguelCompany) [reply rmw_fastrtps_dynamic_cpp/include/rmw_fastrtps_dynamic_cpp/TypeSupport_impl.hpp:562]: The calculation of the sample serialization size is only done for unbounded types (see [here](https://github.com/ros2/rmw_fastrtps/blob/ccb15906683c65911ac632d16360f36edd0d02ac/rmw_fastrtps_dynamic_cpp/include/rmw_fastrtps_dynamic_cpp/TypeSupport_impl.hpp#L928)). For bounded types, the maximum serialized size calculated when constructing the type support object (for instance, [here](https://github.com/ros2/rmw_fastrtps/blob/ccb15906683c65911ac632d16360f36edd0d02ac/rmw_fastrtps_dynamic_cpp/include/rmw_fastrtps_dynamic_cpp/MessageTypeSupport_impl.hpp#L58)) is used.

Knowing the payload size of the sample is needed in order to know the size of the payload that needs to be allocated.

On `rmw_cyclonedds` it is done [here](https://github.com/ros2/rmw_cyclonedds/blob/91aed377a0a2e39664d0eae401ee49e9c419540a/rmw_cyclonedds_cpp/src/serdata.cpp#L210)

**Comment by ivanpauno** [comment]
> @ivanpauno I think builds have failed due to #382

Yes, I always forget that.

CI:
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/12246/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/7223/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/9965/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/12139/)

**Comment by ivanpauno** [comment]
Going in, thanks for the fix @MiguelCompany !!

**Comment by jacobperron** [comment]
This is on the Foxy patch release board, though I'd rather not backport API changes to publicly accessible headers.

@ivanpauno Can you take a look to see if this can be backported in without the changes to API?

**Comment by ivanpauno** [comment]
> This is on the Foxy patch release board, though I'd rather not backport API changes to publicly accessible headers.

Though `Typesupport.hpp` and `Typesupport_impl.hpp` are public headers, nobody uses them.
I don't think this can be fixed without the API changes, IMO it's worth backporting (it's fixing several leaks + potential undefined behavior).

**Comment by nuclearsandwich** [comment]
Bumping this to a future Dashing patch release pending an agreement on the backport discussion above. Dashing will follow Foxy's lead.
